analyzer:
  errors:
    deprecated_member_use: ignore
    avoid_print: ignore
    prefer_final_fields: ignore
    use_super_parameters: ignore
    prefer_const_declarations: ignore
    use_build_context_synchronously: ignore
    empty_catches: ignore
    unnecessary_brace_in_string_interps: ignore
    curly_braces_in_flow_control_structures: ignore
    unnecessary_to_list_in_spreads: ignore
    unused_local_variable: ignore
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - avoid_print
    - use_key_in_widget_constructors